version: 1.0.{build}

image: Visual Studio 2019

cache: c:\tools\vcpkg\installed\

clone_folder: c:\ovpn3\core

install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- .\vcpkg integrate install
- .\vcpkg install asio:x64-windows openssl-windows:x64-windows tap-windows6:x64-windows"
- cd %APPVEYOR_BUILD_FOLDER%\win

platform: x64

configuration: ReleaseOpenSSL

artifacts:
  - path: win\x64\ReleaseOpenSSL\cli.exe
  - path: win\x64\ReleaseOpenSSL\*.dll


